[loggin]
com_desc = "Authorization in the bot via SS14"
arg_desc_login = "Login"
arg_desc_password = "Password"
error = "Authorization error, please check your login or password"
correct = "Authorization successful"
