[loggin]
com_desc = "Авторизация в боте через SS14"
arg_desc_login = "Логин"
arg_desc_password = "Пароль"
error = "Ошибка авторизации, проверьте пожалуйста логин или пароль"
correct = "Авторизация успешна"
